import {readFile,writeFile} from 'node:fs/promises';
import sharp from 'sharp';
const root=new URL('../',import.meta.url);
const read=p=>readFile(new URL(p,root),'utf8');
const write=(p,s)=>writeFile(new URL(p,root),s);
const c=JSON.parse(await read('site.config.json'));
const raw=process.env.SITE_URL||c.url;
const origin=raw?new URL(raw).origin:'';
if(origin&&!origin.startsWith('https://'))throw Error('SITE_URL must use HTTPS');
const ready=!!(origin&&c.operator&&c.email&&c.hostingProvider&&c.hostingPrivacyUrl);
const esc=s=>String(s).replace(/[&<>"']/g,v=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[v]));
const description='Build your own isometric mini golf course, take a shot, and share a challenge. Free to play, with no account needed.';
const contact=`<h2>Operator and contact</h2><p>${esc(c.operator)}<br><a href="mailto:${esc(c.email)}">${esc(c.email)}</a><br><a href="${esc(c.operatorUrl)}">stepanblaha.com</a></p>`;
const pages=[
 ['terms','Terms of use',`<p>Golf This! is a free browser game for building and playing mini golf courses. No account, purchase, or subscription is required.</p><h2>Playing and creating</h2><p>Course physics and scores are for entertainment. A course you create may be impossible to finish. You can edit it or choose a preset to start again.</p><h2>Sharing courses</h2><p>A shared link contains a copy of your course, including its name and an optional score to beat. Anyone with that link can play the course and forward it. The shared view has no course editing controls. Later edits to your saved course do not change copies you already shared. Share only text you have the right to use and avoid including personal or confidential information.</p><h2>Saved progress and availability</h2><p>The current course is saved in this browser when local storage is available. Clearing browser data removes it. Saving may fail in private browsing or when storage is blocked. Keep a course link if you want your own backup. Game progress is not synced between devices.</p><p>The game may change or become unavailable. Continuous availability and error-free operation are not guaranteed. Nothing in these terms limits rights or liability that cannot be limited under applicable law.</p>${contact}`],
 ['privacy','Privacy',`<p>Golf This! runs in your browser. It has no accounts, analytics, advertising, tracking cookies, or server-side course database.</p><h2>Your course stays in your browser</h2><p>Your own current course, including its name and layout, is saved in localStorage under <code>little-links-course</code>. It stays there until replaced or removed by you or your browser. This storage lets you continue editing on a later visit. Delete it using your browser’s settings for this website. Opening a shared course does not replace your saved course. Shots and gameplay run locally. Sound is optional and starts off; enabling it only affects this session.</p><h2>Course links and clipboard</h2><p>Share course copies a link to your clipboard after you press the button. The course is encoded in the part of the URL after the # symbol. That fragment is not sent in the normal HTTP request to our host. Anyone you send the full link to can read its contents, and services you use to share the link may receive them. Course links are not encrypted or access-controlled. A link can also remain in your browser history. Golf This! does not read your clipboard. Challenge scores are supplied by the link creator and are not independently verified.</p><h2>Loading the website</h2><p>The server receives technical connection information, such as your IP address, requested page, and browser information, to deliver the website. Fonts and images are served from this website. ${c.hostingProvider?`Hosting is provided by ${esc(c.hostingProvider)}. ${c.hostingPrivacyUrl?`See the <a href="${esc(c.hostingPrivacyUrl)}">hosting provider’s privacy information</a> for its handling of technical data.`:''}`:''}</p><h2>Contact and your rights</h2><p>If you email the operator, your email address and message are used to respond to your request. Please do not send sensitive information that is unnecessary for your question.</p><p>Where applicable, you can request access, correction, deletion, restriction or portability of your personal data, and object to its processing. Contact the operator below. You may also complain to the <a href="https://uoou.gov.cz/">Czech Office for Personal Data Protection</a>. Read more about <a href="https://commission.europa.eu/law/law-topic/data-protection/information-individuals_en">your data protection rights</a>.</p>${contact}`]
];
const style=`*{box-sizing:border-box}body{margin:0;background:#448bea;color:#23325b;font:16px/1.7 system-ui,sans-serif}main{max-width:760px;margin:48px auto;padding:36px;background:#f2edff;border-radius:26px;box-shadow:0 7px 0 #3273ce}h1{font-size:38px;line-height:1.2}h2{font-size:21px;margin-top:30px}a{color:inherit;text-underline-offset:4px}a:focus-visible{outline:3px solid #23325b;outline-offset:4px}nav{display:flex;justify-content:space-between;gap:20px;font-weight:700;font-size:14px}code{overflow-wrap:anywhere}small{color:#626780}@media(max-width:800px){main{margin:20px 16px;padding:24px}h1{font-size:32px}}`;
for(const [slug,title,body] of pages) await write(`public/${slug}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Golf This!</title><meta name="description" content="${title} for Golf This!, the free mini golf course builder."><meta name="robots" content="${ready?'index,follow':'noindex,nofollow'}">${origin?`<link rel="canonical" href="${origin}/${slug}.html">`:''}<link rel="icon" href="/favicon.svg"><meta name="theme-color" content="#448bea"><style>${style}</style></head><body><main><nav><a href="/">Back to Golf This!</a><a href="/${slug==='terms'?'privacy':'terms'}.html">${slug==='terms'?'Privacy':'Terms'}</a></nav><h1>${title}</h1>${body}<p><small>Last updated: 14 September 2026</small></p></main></body></html>`);
const schema={'@context':'https://schema.org','@type':'WebApplication',name:'Golf This!',description,applicationCategory:'GameApplication',operatingSystem:'Any',inLanguage:'en',isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'EUR'},creator:{'@type':'Person',name:c.operator,url:c.operatorUrl},...(origin?{url:origin+'/'}:{})};
const meta=`<meta name="description" content="${description}"><meta name="author" content="${esc(c.operator)}"><meta name="robots" content="${ready?'index,follow':'noindex,nofollow'}">${origin?`<link rel="canonical" href="${origin}/"><meta property="og:url" content="${origin}/">`:''}<meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:site_name" content="Golf This!"><meta property="og:title" content="Golf This! | Build. Putt. Repeat."><meta property="og:description" content="${description}"><meta property="og:image" content="${origin}/og.png"><meta property="og:image:type" content="image/png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Golf This!: a colorful isometric mini golf course with purple blocks and a red flag."><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Golf This! | Build. Putt. Repeat."><meta name="twitter:description" content="${description}"><meta name="twitter:image" content="${origin}/og.png"><meta name="twitter:image:alt" content="Golf This! isometric mini golf course"><link rel="manifest" href="/site.webmanifest"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>`;
let html=await read('index.html');html=html.replace(/<!-- SEO:START -->[\s\S]*?<!-- SEO:END -->/,'').replace(/<meta name="description"[^>]*>/,'');await write('index.html',html.replace('</head>',`<!-- SEO:START -->${meta}<!-- SEO:END --></head>`));
await write('public/robots.txt',ready?`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
await write('public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${ready?['/','/terms.html','/privacy.html'].map(p=>`<url><loc>${esc(origin+p)}</loc></url>`).join(''):''}</urlset>`);
await write('public/llms.txt',`# Golf This!\n\n> A free browser-based isometric mini golf course builder and game. No registration.\n\n## Pages\n- [Play and build](${origin}/)\n- [Terms](${origin}/terms.html)\n- [Privacy](${origin}/privacy.html)\n\n## How it works\nGenerate a random course with a clear path or build an 8 by 8 course using grass, blocks, sand, water, a tee, and a hole. Play with drag-to-putt or aim and power controls. Water adds a penalty stroke after taking a drop. Share links encode a copy of the course and an optional challenge score in the URL fragment. Your own course is saved locally in the browser. Shared links open in play-only mode with no editing controls and do not overwrite the saved course. There is no online course database or multiplayer server.\n\n## Operator\n${c.operator}\n${c.email}\n${c.operatorUrl}\n`);
await write('public/site.webmanifest',JSON.stringify({name:'Golf This!',short_name:'Golf This!',lang:'en',start_url:'/',display:'browser',background_color:'#448bea',theme_color:'#448bea',icons:[{src:'/icon-192.png',sizes:'192x192',type:'image/png'},{src:'/icon-512.png',sizes:'512x512',type:'image/png'}]},null,2));
const logo=Buffer.from(await read('public/favicon.svg'));
for(const [name,size] of [['icon-192',192],['icon-512',512],['apple-touch-icon',180]])await sharp(logo).resize(size,size).flatten({background:'#448bea'}).png().toFile(new URL(`public/${name}.png`,root).pathname);
if(!ready)console.log('Preview metadata generated. Complete production URL and hosting details in site.config.json before launch.');
if(process.argv.includes('--check')&&!ready)process.exitCode=1;
